sudo: required
os: osx

language: generic
osx_image: xcode8

env: MAVEN_PUBLISH_OS_TYPE=osx-x86_64-cpu mxnet_variant=cpu

# addons:
# homebrew:
# update: true
# packages:
# - pkg-config
# - graphviz
# - pyenv
# - coreutils
# - openssl
# - gnupg@1.4
# - automake
# - opencv
# - nasm
 
before_install: |
  travis_wait rvm get head --auto-dotfiles;
  travis_wait brew update;
  travis_wait brew install openssl
  travis_wait brew install gnupg@1.4
  export PATH=/usr/local/opt/gnupg@1.4/libexec/gpgbin:$PATH
  travis_wait brew install automake
  travis_wait brew install pkg-config
  travis_wait brew install nasm
  # travis_wait brew install maven


script:
  - git clone https://github.com/zachgk/incubator-mxnet -b automate-maven
  - cd incubator-mxnet
  - git rev-parse HEAD
  - ./ci/publish/scala/fullDeploy.sh

